### ISSUE TITLE
I have a problem about PathCNN_GradCAM.py

### ISSUE THREAD

**Issue by MrAirplaneLu** [mskspi/PathCNN#2]
![image](https://user-images.githubusercontent.com/45754132/135755145-c30fe7b7-9d01-4030-8821-fedc618c59d0.png)

**Comment by taznux** [comment]
I fixed the issue, and here is a colab notebook for testing.
https://colab.research.google.com/drive/1WCfguKFN0Zs0ZDkKga2DpDgjBP3PnwB_?usp=sharing
