### ISSUE TITLE
Question about pathway in KEGG

### ISSUE THREAD

**Issue by Y-Claw** [mskspi/PathCNN#4]
Hi,
    When I tried to replicate your experiment from scratch, I found some pathways that were not found in the KEGG hsa pathway, such as SELENOAMINO_ACID_METABOLISM and DORSO_VENTRAL_AXIS_FORMATION. VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS contains only 4 genes in the hsa pathway, which cannot be processed into 5-dimensional data using PCA. Could you please provide more details about pathway and the genes used in pathway?

**Comment by mskspi** [comment]
Hi,
We used only 146 KEGG pathways that are available in the 'data' folder, removing disease-specific pathways. For associated genes for each pathway, the c2.cp.kegg.v5.2.symbols.gmt was used, which was downloaded from the gsea-msigdb database.

**Comment by Y-Claw** [comment]
Get it, thank you very much.
